### ISSUE TITLE
@Secret is not working when data class has a subclass

### ISSUE THREAD

**Issue by mkopylec** [aafanasev/sekret#17]
This:
```kotlin
abstract class Base(@Secret open val secret: String)

data class Specific(
    @Secret override val secret: String,
    @Secret val other: String
) : Base(secret)

fun main() {
    println(Specific("secret value", "other value"))
}
```
prints:
```
Specific(secret=secret value, other=***)
```
but should print:
```
Specific(secret=***, other=***)
```

**Comment by aafanasev** [comment]
Thanks for reporting. The thing is `override val secret: String` gets compiled to `getSecret(): String`. And functions are not supported by Sekret. I'll add it in the next version.

Meanwhile, as a workaround I'd suggest you to rename the property and remove `override` as:
```kotlin
data class Specific(
    @Secret val str: String,
    @Secret val other: String
) : Base(str)
```

**Comment by mkopylec** [comment]
Great, I'm waiting for the next version then.

**Comment by aafanasev** [comment]
Try out 0.0.8 version.

**Comment by mkopylec** [comment]
Still not working :(

**Comment by aafanasev** [comment]
@mkopylec please try againg `0.0.10` version. I forgot to update dependencies.

**Comment by mkopylec** [comment]
```
Execution failed for task ':login-service:kaptGenerateStubsKotlin'.
> Could not resolve all files for configuration ':login-service:kotlinCompilerPluginClasspath'.
   > Could not find dev.afanasev:sekret-kotlin-plugin:0.0.10.
```

**Comment by mkopylec** [comment]
Any update here?

**Comment by aafanasev** [comment]
Blocked by https://github.com/aafanasev/sekret/issues/19

The fix is ready but `jcenter` is deprecated. Therefore, I've uploaded to `mavenCentral` (https://search.maven.org/artifact/net.afanasev/sekret-annotation). 

Once my gradle (https://plugins.gradle.org/plugin/net.afanasev.sekret) plugin gets approved I'll update README as there is breaking changes.

**Comment by mkopylec** [comment]
Great, I'm waiting for it.

**Comment by aafanasev** [comment]
Released https://github.com/aafanasev/sekret/releases/tag/0.1.0

**Comment by mkopylec** [comment]
It works, thanks
