### ISSUE TITLE
Latest released version of plugin doesn't match latest library version

### ISSUE THREAD

**Issue by ryanlewis** [aafanasev/sekret#32]
The badge in the README currently states the latest version being 0.1.3, but the latest gradle plugin available on Maven Central shows as 0.1.2.

https://mvnrepository.com/artifact/net.afanasev/sekret-gradle-plugin

![image](https://user-images.githubusercontent.com/427747/183914141-f7caf087-8af9-4acd-95d4-f0767e9793e6.png)

Ideally, would be nice if the plugin version was the same as the latest version of the package, as can then leverage version references with Gradle Version Catalogs.

**Comment by aafanasev** [comment]
Thanks for reporting. 

Gradle Plugins portals shows 0.1.3 as the latest available version https://plugins.gradle.org/plugin/net.afanasev.sekret

Honestly, I have no idea how mvnrepository.com syncs with https://plugins.gradle.org/m2/net/afanasev/sekret-gradle-plugin/0.1.3/
