### ISSUE TITLE
Plugin doesn't work with newer versions of Kotlin

### ISSUE THREAD

**Issue by ryanlewis** [aafanasev/sekret#33]
toString() on data classes just gives a default toString implementation as if it's a normal class.

**Comment by aafanasev** [comment]
Thanks for reporting. Looking...

**Comment by aafanasev** [comment]
Release 0.1.4. Please check.

**Comment by ryanlewis** [comment]
Seems to have done the trick, thank you!

Raising another ticket for another issue I've noticed in testing.
